### PR TITLE
style(badge): change naming of badge themes

### PR DESCRIPTION
**Pull request by matanmoda**

### CODE REVIEW

**Review by NataliaAlesencova — DISMISSED** [review]

**Comment by bjmiller** [comment]
Note that this is a breaking change.

**Comment by matanmoda** [comment]
> Note that this is a breaking change.

@bjmiller anything specific should change? version number or type of commit?

**Comment by bjmiller** [comment]
Yes.  This should go to 16.0.0, not 15.7.1 .  But, since you didn't put that in the commit message, I guess it's a bit late.  Please make sure that this doesn't break anywhere else, such as Stylist or new Vendor Portal.

**Comment by matanmoda** [comment]
> Yes. This should go to 16.0.0, not 15.7.1 . But, since you didn't put that in the commit message, I guess it's a bit late. Please make sure that this doesn't break anywhere else, such as Stylist or new Vendor Portal.

I ran a search in all the codebases.. seems to only affect facade.. 😵‍💫

**Review by bjmiller — APPROVED** [review]

**Pull request merged**
