### PR TITLE
feat(select): improve keyboard navigation

### PR DESCRIPTION
**Pull request by hevele-moda**
Allow searching by keywords and scroll active element into view.
Also copied [use-keyboard-list-navigation](https://github.com/dzucconi/use-keyboard-list-navigation) into the repo because I don't have push access to that repo.

### CODE REVIEW

**Review by norbertorok92 — APPROVED** [review]

**Comment by dzucconi** [comment]
@hevele-moda I'm gonna port this over to the lib. For some reason this repo 500s anytime anyone attempts to pull request against it — is that what happened? I'm being ignored by Github support 😞

**Comment by hevele-moda** [comment]
> @hevele-moda I'm gonna port this over to the lib. For some reason this repo 500s anytime anyone attempts to pull request against it — is that what happened? I'm being ignored by Github support 😞

Yeah my push got rejected and then I tried to open an issue in the repo but I got a 500, so I gave up 😄

**Comment by dzucconi** [comment]
@hevele-moda thx for the features. I just wanted to add them in two separate pull requests but forgot about the 500 thing.

I changed the option name from `defaultSelected` to `defaultValue` which I thought was a bit more idiomatic.

https://twitter.com/dzucconi/status/1304078654075437060 🙄 maybe I should just re-initialize that repo. Super weird that you can't even make issues.

**Pull request merged**
